### ISSUE TITLE
XenServer 7.0 can not start VM after running netinstall.sh

### ISSUE THREAD

**Issue by truongtx8** [rposudnevskiy/RBDSR#34]
Installation goes smooth and everything seems right but our XenServer broke after installation.
`# xe vm-start vm=UXVN0016`
`There was an SR backend failure.
status: non-zero exit
stdout:`
`stderr: Traceback (most recent call last):
  File "/opt/xensource/sm/NFSSR", line 295, in <module>
    SRCommand.run(NFSSR, DRIVER_INFO)
  File "/opt/xensource/sm/SRCommand.py", line 352, in run
    ret = cmd.run(sr)
  File "/opt/xensource/sm/SRCommand.py", line 110, in run
    return self._run_locked(sr)
  File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
    rv = self._run(sr, target)
  File "/opt/xensource/sm/SRCommand.py", line 264, in _run
    writable, caching_params)
  File "/opt/xensource/sm/blktap2.py", line 1560, in activate
    if self._activate_locked(sr_uuid, vdi_uuid, options):
  File "/opt/xensource/sm/blktap2.py", line 86, in wrapper
    ret = op(self, *args)
  File "/opt/xensource/sm/blktap2.py", line 1607, in _activate_locked
    dev_path = self._activate(sr_uuid, vdi_uuid, options)
  File "/opt/xensource/sm/blktap2.py", line 1651, in _activate
    self._get_pool_config(sr_uuid).get("mem-pool-size"))
  File "/opt/xensource/sm/blktap2.py", line 1305, in _tap_activate
    options)
  File "/opt/xensource/sm/blktap2.py", line 810, in launch_on_tap
    exc_info = sys.exc_info()`
`NameError: global name 'sys' is not defined`

Update 1: restored /sbin/tap-ctl back to original version, problem fixed.

**Comment by rposudnevskiy** [comment]
Hi,
Please check the latest version (commit [d7b62cf](https://github.com/rposudnevskiy/RBDSR/commit/d7b62cfb11d07352f3989fda19a6cef29752be5e))
Thank you for you help with testing.
Roman
