### ISSUE TITLE
v3.0 import .ova images directly to ceph storage doesn't work

### ISSUE THREAD

**Issue by northbear** [rposudnevskiy/RBDSR#84]
It cause error message. /var/log/SMlog contains: 

`Aug 20 14:42:59 xcp-tst SMAPIv3: [7827] - ERROR - Unhandled exception#012Traceback (most recent call last):#012  File "/usr/libexec/xapi-storage-script/volume/org.xen.xapi.storage.rbdsr/Volume.create", line 9, in <module>#012    from xapi.storage.libs.librbd.volume import RAWVolume, QCOW2Volume#012  File "/usr/lib/python2.7/site-packages/xapi/storage/libs/librbd/volume.py", line 14, in <module>#012    from xapi.storage.libs.librbd.datapath import QdiskDatapath as Datapath#012  File "/usr/lib/python2.7/site-packages/xapi/storage/libs/librbd/datapath.py", line 5, in <module>#012    from xapi.storage.libs.librbd import tapdisk, qemudisk, meta#012ImportError: cannot import name tapdisk
`

**Comment by northbear** [comment]
The same issue arise if trying to move image from local storage to Ceph. And on create new VM...

**Comment by rposudnevskiy** [comment]
Hi,
I will make a fix a little bit later, 
but you can remove `tapdisk` from line 5 of `/usr/lib/python2.7/site-packages/xapi/storage/libs/librbd/datapath.py`
The line should look like this:
`from xapi.storage.libs.librbd import qemudisk, meta`

**Comment by northbear** [comment]
yeah... It helps. 
But it still doesn't work properly. disk image is copied to ceph storage successfully, but VM building fails without any warnings. It looks like it tries to build VM when copying disk image is not completed yet... 
Should I open other issue for it?

**Comment by rposudnevskiy** [comment]
Could you please send me SMlog and xensource.log?

**Comment by northbear** [comment]
Sorry for delaying. I'll provide it later when we'll turn back to test XCP-ng 7.5 and RBDSR v3.0 plugin configuration.

**Comment by northbear** [comment]
It looks that with current v3.0 plugin it works but not correctly. It starts, shows progress bar and stuck after that for long time. After disconnecting XCP-Center from xcp cluster and connecting newly, the image appears as like it was imported successfully. The image works properly. 
It looks like operation is not completed/finalized properly. Logs attached below: 
[SMlog.full-copy-stale.log](https://github.com/rposudnevskiy/RBDSR/files/2483099/SMlog.full-copy-stale.log)
[xensource.log.full-copy-stale.log](https://github.com/rposudnevskiy/RBDSR/files/2483100/xensource.log.full-copy-stale.log)

**Comment by northbear** [comment]
It looks like image copying should be implement as task.
