### ISSUE TITLE
7.5 ceph mimic error pdb-plug

### ISSUE THREAD

**Issue by linuxmanxxx** [rposudnevskiy/RBDSR#86]
Error parameters: /usr/libexec/xapi-storage-script/volume/org.xen.xapi.storage.rbdsr/SR.attach, non-zero exit and bad json on stdout, 1, ,

**Comment by linuxmanxxx** [comment]
Sep  6 15:47:37 zen4 SMAPIv3: [28772] - ERROR - Unhandled exception#012Traceback (most recent call last):#012  File "/usr/libexec/xapi-storage-script/volume/org.xen.xapi.storage.rbdsr/SR.attach", line 12, in <module>#012    from xapi.storage.libs.librbd import utils, ceph_utils, rbd_utils, meta#012  File "/usr/lib/python2.7/site-packages/xapi/storage/libs/librbd/ceph_utils.py", line 3, in <module>#012    import rados#012ImportError: No module named rados
What should provide the module as it's not present? I did the install of the rpm stormie provided as well as your v3 install.

**Comment by linuxmanxxx** [comment]
Ok figured I missed the part up top saying what had to be installed and then got past it and then no SR was attached error now:
There was an SR backend failure.
status: Sr_not_attached

**Comment by linuxmanxxx** [comment]
ok beside this plugin for rbd can cephfs support be added as well which would give a clusterable SR as well?

**Comment by linuxmanxxx** [comment]
Ok I already have rbd setup simply as rbd. Where in the config on the virtual do I present that as what is my repository instead of the name-uuid you setup in the instructions for api 3? Instead of telling people what to do on ceph give them instructions on how to attach to existing rbd devices since I'm sure most will already have that part configured well before adding xcp-ng to the mix.
