### ISSUE TITLE
Have some error,can't create SR

### ISSUE THREAD

**Issue by kenneth104** [rposudnevskiy/RBDSR#99]
Hava some file in
`RBDSR-3.0/xapi/storage/libs/xcpng/librbd
`
But, the install.sh do nothing with this file

After manual operation

`tail /var/log/SMlog`

```
Feb 15 14:56:01 node5-192 SMAPIv3: [7953] - INFO - called as: ['/usr/libexec/xapi-storage-script/volume/org.xen.xapi.storage.rbdsr/Plugin.Query', '--json']

Feb 15 14:56:01 node5-192 SMAPIv3: [7955] - ERROR - Unhandled exception#012Traceback (most recent call last):#012  File "/usr/libexec/xapi-storage-script/volume/org.xen.xapi.storage.rbdsr/SR.create", line 14, in <module>#012    from xapi.storage.libs.xcpng.librbd.sr import Implementation, SR#012  File "/usr/lib/python2.7/site-packages/xapi/storage/libs/xcpng/librbd/sr.py", line 7, in <module>#012    from xapi.storage.libs.xcpng.sr import Implementation#012ImportError: No module named sr
```

**Comment by rposudnevskiy** [comment]
Hi,
Sorry for this. The plugin was fully rewritten using xcpng-storage-libs but I have not had time to fix the install script.
Hope to fix it soon

**Comment by kenneth104** [comment]
Thanks a lot
When using Ceph-iscsi have poor performance,and i don't know how  to delete iscsi-gateway
https://github.com/ceph/ceph-iscsi-cli/issues/151

need test RBDSR （Have been properly installed and tested before）
Have a nice day

**Comment by 0x6263** [comment]
> Sorry for this. The plugin was fully rewritten using xcpng-storage-libs but I have not had time to fix the install script.
Hope to fix it soon

I tried to install the latest version on a xcp-ng 7.6 server, as you already said the install script is not working anymore.
Is there a way that I can help you for the migration? If you can give me a note what you try to accomplish and what your plan is regarding how the new installation should work, maybe I can do some of the implementation and testing work.

Bye
